import { cableSpecifications, cableComparisonRows, oilCableDimensions, oilCableEnvironment, oilCableChemistry, oilCableCurrentHeadings, oilCableCurrentOil, oilCableCurrentGas } from "@/lib/cable-data";
import { SpecificationTable } from "./selectors";
import { Eyebrow } from "./site";

export function CableSpecifications() {
  return <section className="cable-specifications"><Eyebrow>GEOTHERMAL POWER CABLES</Eyebrow><h2>Two constructions. Clear specifications.</h2><p className="section-intro">Flat, three-core power cables for submersible motors. Compare the fluoropolymer-sheathed REPN-FX and lead-sheathed REPN-QX constructions for your operating conditions.</p>
    <div className="cable-models">{cableSpecifications.map(cable => <article key={cable.code}><div className="cable-model-title"><div><p>5 kV · 3 × 33.5 mm²</p><h3>{cable.code}</h3></div><span>{cable.temperature}<small>°C rating</small></span></div><ol aria-label={`${cable.code} construction, conductor to armour`}>{cable.layers.map((layer,index) => <li key={layer}><span>{index+1}</span>{layer}</li>)}</ol><p className="cable-envelope">Maximum overall size <strong>{cable.size}</strong></p></article>)}</div>
    <SpecificationTable caption="ESP cable specifications — REPN-FX and REPN-QX" headings={["Parameter", "REPN-FX", "REPN-QX"]} rows={cableComparisonRows}/>
    <p className="spec-note">Temperature values are specified cable ratings. Allowable current, fluid compatibility, installation clearance and motor connection must be checked for the complete system. The two constructions have different temperature ratings and are not interchangeable solely because both are rated 5 kV.</p>
    <div className="technical-subsection"><Eyebrow>QUALITY DOCUMENTATION</Eyebrow><h3>Electrical and construction checks.</h3><p>Batch reports for both cable types record dimensional checks, conductor resistance, insulation resistance, AC and DC voltage tests, and longitudinal gas-leakage tests. Request the applicable documentation with your equipment enquiry.</p></div>
  </section>;
}

export function OilfieldCableSpecifications() {
 const armours=[{title:"Galvanized-steel armour",detail:"Production-water pH 5.0–8.5",armour:"Galvanized steel tape"},{title:"Corrosion-resistant armour",detail:"Production-water pH 3.0–9.0",armour:"Corrosion-resistant steel or Monel alloy"}];
 return <section className="cable-specifications oilfield-cables"><Eyebrow>OIL &amp; GAS POWER CABLES</Eyebrow><h2>EPR insulation. Lead-sheathed protection.</h2><p className="section-intro">Flat, three-core copper cables for oilfield submersible motors. The 5 kV, 50 Hz reference construction has a maximum continuous conductor temperature of 230 °C and two armour options.</p>
 <div className="cable-models">{armours.map(item=><article key={item.title}><div className="cable-model-title"><div><p>5 kV AC · 50 Hz</p><h3>{item.title}</h3></div><span>230<small>°C conductor</small></span></div><ol aria-label={`${item.title}, conductor to armour`}>{["Solid copper conductor","Ethylene propylene rubber (EPR) insulation","Lead sheath around each insulated core","Non-woven tape wrapping",item.armour].map((layer,i)=><li key={layer}><span>{i+1}</span>{layer}</li>)}</ol><p className="cable-envelope">Fluid compatibility <strong>{item.detail}</strong></p></article>)}</div>
 <h3>Dimensions &amp; conductor sizes</h3><SpecificationTable caption="5 kV oilfield cable reference dimensions. Overall size is maximum thickness × width." headings={["Cores × area, mm²","Nominal conductor Ø, mm","Maximum overall size, mm"]} rows={oilCableDimensions}/>
 <p className="spec-note">Nominal EPR insulation thickness: 2.0 mm. Nominal lead sheath thickness: 0.85 mm. Dimensions apply to this reference construction; confirm the supplied configuration and installation clearance.</p>
 <h3>Operating environment</h3><SpecificationTable caption="Fluid limits for the 5 kV oilfield reference construction" headings={["Parameter","Galvanized-steel armour","Corrosion-resistant armour"]} rows={oilCableEnvironment}/>
 <details className="cable-detail"><summary>Additional fluid limits for corrosion-resistant armour</summary><SpecificationTable caption="Maximum concentrations for the corrosion-resistant reference construction" headings={["Constituent","Maximum, g/L"]} rows={oilCableChemistry}/></details>
 <details className="cable-detail"><summary>Continuous current ratings by temperature</summary><p>Maximum continuous current in amperes (A), by conductor cross-section and ambient temperature. The 230 °C rating is the conductor limit, not the ambient temperature at full load.</p><SpecificationTable caption="Maximum continuous current (A) — oil well fluid" headings={oilCableCurrentHeadings} rows={oilCableCurrentOil}/><SpecificationTable caption="Maximum continuous current (A) — gas-air environment" headings={oilCableCurrentHeadings} rows={oilCableCurrentGas}/><p className="spec-note">Request a confirmed current rating for 13.3 mm². Select allowable current for the actual installation and fluid conditions.</p></details>
 </section>;
}
