import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { Eyebrow } from "./site";
import { SpecificationTable } from "./selectors";

export function CompanyContent() {
 return <>
  <section className="container company-profile" id="company-profile" aria-labelledby="company-profile-title">
   <div className="company-profile-heading"><Eyebrow>THE COMPANY</Eyebrow><h2 id="company-profile-title">Focused on your<br/>pumping project.</h2><p className="company-established"><span>Established</span><strong>August 2024</strong></p></div>
   <div className="company-profile-copy"><p>REPN-FZCO focuses on electric submersible pumping equipment for geothermal energy and oil &amp; gas production.</p><p>The company coordinates project requirements, equipment selection and the agreed supply and service scope. Each configuration is considered against the operating conditions and the needs of the project.</p></div>
  </section>
  <section className="company-process"><div className="container company-next">
   <div className="interior-section-heading"><div><Eyebrow>WORKING WITH REPN-FZCO</Eyebrow><h2>From requirements<br/>to an agreed scope.</h2></div></div>
   <div className="company-route-grid">
    <Link href="/equipment/" className="company-route"><span className="company-route-number" aria-hidden="true">01 / EQUIPMENT</span><h3>Equipment portfolio</h3><p>Explore product specifications and available equipment configurations.</p><span className="company-route-action">Find your equipment<ArrowUpRight size={21}/></span></Link>
    <Link href="/services/" className="company-route"><span className="company-route-number" aria-hidden="true">02 / SERVICES</span><h3>Project &amp; service support</h3><p>Review the available areas of support through the ESP lifecycle.</p><span className="company-route-action">Explore services<ArrowUpRight size={21}/></span></Link>
   </div>
  </div></section>
 </>;
}

export function CatalogueDetail({slug}:{slug:string}) {
  if(slug==="pumps") return <section className="technical-subsection" id="configuration"><Eyebrow>GEOTHERMAL / CONSTRUCTION OPTIONS</Eyebrow><h2>The materials inside the pump.</h2><p className="section-intro">Stage assembly and material options allow the configuration to reflect the fluid and mechanical requirements of the well.</p><SpecificationTable caption="Geothermal pump construction options. Options depend on the selected configuration." headings={["Component","Catalogue construction / options"]} rows={[
    ["Radial bearings","VK8-V hard alloy"],
    ["Stages","Ni-resist cast iron; stainless powder-alloy option"],
    ["Shaft","High-strength corrosion-resistant steel; Alloy 925 (718) options"],
    ["End parts","Structural steel; stainless steel for corrosion-resistant versions"],
    ["Fasteners","Structural alloy steel; K-Monel options"],
    ["Corrosion-resistant housings","Metallic protective coating"]
  ]}/><div className="info-columns"><div><h3>TP and QJ construction</h3><p>TP diffusers are assembled inside a housing. QJ uses bolted diffusers without a continuous outer housing.</p></div><div><h3>Stage-assembly codes</h3><p>FLT identifies floater construction; PKT identifies packet construction; CPM identifies compression construction.</p></div></div><SpecificationTable caption="Geothermal pump designation" headings={["Code","Meaning"]} rows={[["AR1","Abrasion-resistant configuration: solids up to 500 mg/L"],["AR2","Abrasion-resistant configuration: solids up to 1,000 mg/L"],["CR","Corrosion-resistant configuration"]]}/></section>;
  if(slug==="motors") return <section className="technical-subsection" id="configuration"><Eyebrow>728 SERIES / MOTOR CONFIGURATION</Eyebrow><h2>Temperature and material options.</h2><p className="section-intro">The geothermal permanent magnet motor uses a rare-earth permanent-magnet rotor. Its catalogue designation identifies the thermal class, corrosion-resistant construction and sensor option.</p><SpecificationTable caption="Geothermal motor designation" headings={["Thermal code","Fluid-temperature rating","Housing OD"]} rows={[["Standard","120 °C","185 mm"],["HT","160 °C","185 mm"],["UHT","200 °C","185 mm"]]}/><SpecificationTable caption="Corrosion-resistant motor configurations" headings={["Code","Construction"]} rows={[["CR2C","Thermal-spray coating on housing, head and base"],["CR1S","Stainless-steel head and base; housing without thermal-spray coating"],["CR2S","Stainless-steel head and base; thermally sprayed housing"]]}/><p className="spec-note">The selected temperature class, motor rating and required cooling-flow velocity must be considered together. The table lists fluid-temperature configurations, not a single rating for every motor.</p></section>;
  if(slug==="protectors") return <section className="technical-subsection" id="configuration"><Eyebrow>GEOTHERMAL / SEAL-SECTION DESIGN</Eyebrow><h2>How the protector works.</h2><div className="info-columns three"><div><h3>Separate the fluids</h3><p>Diaphragms and mechanical seals form barriers between well fluid and the motor’s internal oil.</p></div><div><h3>Accommodate expansion</h3><p>Chambers allow for changes in motor-oil volume as the system heats and cools.</p></div><div><h3>Support the assembly</h3><p>The protector transmits torque and provides thrust-bearing support within the ESP assembly.</p></div></div><SpecificationTable caption="Tandem protector configuration" headings={["Code / item","Catalogue meaning"]} rows={[["LSB / BSL","Labyrinth and diaphragm (bag) chamber sequence"],["STL / HL","Standard / reinforced thrust-bearing configuration"],["HT / UHT","160 °C / 200 °C thermal configuration"]]}/><p className="spec-note">The catalogue also describes sand-drainage holes, a sealing cup and bypass pressure balancing. Confirm the chamber layout and thrust capacity for the selected assembly.</p></section>;
  if(slug==="sensors") return <section className="technical-subsection" id="configuration"><Eyebrow>GEOTHERMAL / MEASUREMENT SCOPE</Eyebrow><h2>Monitor what happens downhole.</h2><SpecificationTable caption="Downhole monitoring" headings={["Measurement","Configuration"]} rows={[["Downhole environment temperature","Monitored parameter"],["Downhole environment pressure","Monitored parameter"],["Permanent magnet motor oil temperature","Monitored parameter"],["Pump-outlet temperature and pressure","Optional measurements"],["Flow rate","Optional measurement"]]}/><div className="info-columns"><div><h3>Monitoring from start-up</h3><p>The catalogue describes automatic monitoring from start-up and integration with protective control functions when critical operating parameters are reached.</p></div><div><h3>Part of the system</h3><p>The sensor is supplied as part of the motor and control configuration. A stainless-steel housing coating is described for corrosion protection.</p></div></div></section>;
  if(slug==="controls") return <section className="technical-subsection" id="configuration"><Eyebrow>GEOTHERMAL / VSD DETAILS</Eyebrow><h2>Electrical ratings &amp; interfaces.</h2><SpecificationTable caption="VSD specifications. Rating and enclosure depend on the selected drive." headings={["Parameter","Catalogue specification"]} rows={[["380 V input tolerance","−25% / +25%"],["480 V input tolerance","−25% / +10%"],["Output frequency resolution","0.1 Hz"],["Drive current range","63–1,837 A"],["Input pulse options","6 / 12 / 18 pulse"],["Maximum ambient temperature","55 °C"],["Minimum temperature with heaters","−40 °C"],["Enclosure options","NEMA 3R / NEMA 4"],["Serial interface","RS485, 9.6–115 kbps; Modbus Slave"],["Analogue interfaces","0–10 V / 4–20 mA"],["Digital interfaces","24 V DC"],["Logs","Fault and event logging; USB access"]]}/><p className="spec-note">The catalogue describes stuck-pump start and shaking functions, gas-lock ride-through and compatibility with induction and permanent magnet motors.</p></section>;
  if(slug==="gas-handling") return <section className="technical-subsection" id="configuration"><Eyebrow>OILFIELD / TECHNICAL MODELS</Eyebrow><h2>Separation and dispersion.</h2><p className="section-intro">In a hydrocyclone, gas is directed toward the vortex centre for discharge, while liquid moves along the housing sleeve toward the pump.</p><SpecificationTable caption="Selected technical designs. Values apply only to the described modules." headings={["Module","Intake gas content","Separation ratio"]} rows={[["Hydrocyclone gas separator","≤ 70%","≤ 87%"],["Hydrocyclone separator–dispersant","≤ 75%","≤ 87%"],["Hydrocyclone with upgraded dispersing unit","≤ 80%","≤ 87%"],["Hydrocyclone with double upgraded dispersing unit and dynamic gas outlet","≤ 90%","≤ 90%"]]}/><div className="info-columns"><div><h3>Wear and corrosion options</h3><p>Selected configurations use hard-alloy radial bearings, Ni-Cr stainless-steel protective sleeves, stainless end parts and shafts, and Ni-resist flow components.</p></div><div><h3>Load transfer</h3><p>Gas-stabilizing modules have no axial support of their own; the load is transferred to the seal-section thrust bearing.</p></div></div></section>;
  return null;
}
