import { AssetImage } from "./asset-image";
import Link from "next/link";
import { TechnicalImage } from "./technical-image";
import { ArrowUpRight, ChevronRight, Download, FileText } from "lucide-react";
import { Button, Eyebrow, EnquiryCTA } from "./site";
import { PumpSelector, MotorSelector, EnquiryForm, EquipmentFilter, SpecificationTable } from "./selectors";
import { equipment } from "@/lib/repn-data";
import { downloads, enquiryHref } from "@/lib/site-structure";
import { CompanyContent, CatalogueDetail } from "./catalogue-content";
import { CableSpecifications, OilfieldCableSpecifications } from "./cable-specifications";
import { ProductBreadcrumb, ProductWorkspace, CableHeadingMark } from "./product-workspace";

export function PageHero({label,title,intro,crumb}:{label:string;title:string;intro:string;crumb?:string}) {
 return <section className="page-hero"><div className="container">
  <nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link><ChevronRight size={13}/>{crumb&&<><Link href="/equipment/">Equipment</Link><ChevronRight size={13}/></>}<span aria-current="page">{crumb||label}</span></nav>
  <Eyebrow>{label}</Eyebrow><h1>{title}</h1><p className="intro">{intro}</p>
 </div></section>;
}
function FeatureHero({ label, title, intro, image, alt, caption, target, action }: { label: string; title: string; intro: string; image: string; alt: string; caption: string; target: string; action: string }) {
 return <section className="feature-hero"><div className="container">
  <nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link><ChevronRight size={13}/><span aria-current="page">{label}</span></nav>
  <div className="feature-hero-frame">
   <div className="feature-hero-copy"><Eyebrow>{label}</Eyebrow><h1>{title}</h1><p>{intro}</p><a href={target} className="feature-hero-link">{action}<ArrowUpRight size={19}/></a></div>
   <figure className="feature-hero-photo"><AssetImage src={image} alt={alt} loading="eager"/><figcaption>{caption}</figcaption></figure>
  </div>
 </div></section>;
}

export function EquipmentPage(){return <main id="main" className="interior-page equipment-page"><PageHero label="Equipment portfolio" title="Equipment for your application." intro="Choose an application, then find the component you need. Product pages bring together specifications, options and available data sheets."/><section className="container page-content"><EquipmentFilter/></section><EnquiryCTA/></main>;}

export function ProductPage({slug}:{slug:string}) {
 const product=equipment.find(item=>item.slug===slug)!;
 const photos: Record<string, {alt: string; caption: string}> = {
  pumps: {alt: "ESP pump assemblies with flanged connections", caption: "ESP pump assemblies · original equipment photo"},
  motors: {alt: "Submersible motor assemblies", caption: "Motor assemblies"},
  coatings: {alt: "HVOF coating process", caption: "HVOF coating · original equipment photo"},
 };
 const photo=photos[slug];
 return <main id="main" className="interior-page product-page">
  <section className="product-heading"><div className="container"><ProductBreadcrumb name={product.name}/>
   <div className="product-heading-grid">
    <div className="product-heading-copy"><Eyebrow>{product.tag}</Eyebrow><h1>{product.name}</h1><p className="product-heading-summary">{product.description}</p></div>
    {slug==="cables"?<CableHeadingMark/>:<TechnicalImage className={`product-heading-image product-image-${slug} ${photo?"product-photo":""}`} src={`/assets/${product.image}.webp`} alt={photo?.alt??product.name} caption={photo?.caption??"Product illustration"}/>}
   </div>
  </div></section>
  <ProductTechnical slug={slug}/>
 </main>;
}

function ProductTechnical({slug}:{slug:string}) {
 const product=equipment.find(item=>item.slug===slug)!;
 if(slug==="pumps") return <ProductWorkspace slug={slug} name={product.name} panes={[{application:"geothermal",content:<><section id="geothermal"><Eyebrow>GEOTHERMAL PUMPS</Eyebrow><h2>Select a series.</h2><p className="section-intro">Compare the single-stage operating point and view the original performance curve for each pump family.</p><PumpSelector/><CatalogueDetail slug="pumps"/></section></>},{application:"oil-and-gas",content:<><section id="oilfield"><Eyebrow>OILFIELD PUMPS</Eyebrow><h2>362, 400 and 512 series.</h2><p className="section-intro">Modular centrifugal pumps for formation-fluid production. The catalogue portfolio spans approximately 315–3,144 BPD and provides floater and packet stage-assembly options.</p><SpecificationTable caption="Oilfield pump series" headings={["Series","Housing OD","Portfolio context"]} rows={[["362","92 mm / 3.62 in","Modular centrifugal pump"],["400","103 mm / 4.06 in","Modular centrifugal pump"],["512","130 mm / 5.12 in","Modular centrifugal pump"]]}/><SpecificationTable caption="Oilfield pump designation — configuration options" headings={["Code","Meaning"]} rows={[["FLT","Floater stage assembly"],["PKT","Packet stage assembly"],["S11–S14","Stainless-steel shaft options, 1,080–1,370 MPa yield point"],["M11–M14","Alloy 925 (718) shaft options, 1,080–1,370 MPa yield point"],["CR","Corrosion-resistant housing configuration"]]}/><div className="curve-request"><div><Eyebrow>PERFORMANCE CURVES</Eyebrow><h3>Get the curve for your operating point.</h3><p>Oilfield performance curves are supplied for the selected pump model and speed. Include flow, required head and fluid conditions so the head, power and efficiency curves can be matched to your application.</p></div><Link className="button button-outline" href={enquiryHref("Oilfield pump performance curves","oil-and-gas")}>Request pump curves<ArrowUpRight size={18}/></Link></div><p className="spec-note">Catalogue values are reference data. Final series, stage count, materials and operating range are confirmed against the actual well conditions.</p></section></>}]} />;
 if(slug==="motors") return <ProductWorkspace slug={slug} name={product.name} panes={[{application:"geothermal",content:<><section id="geothermal"><Eyebrow>GEOTHERMAL / 728 SERIES</Eyebrow><h2>Permanent magnet motors.</h2><p className="section-intro">185 mm housing diameter. Select the rated speed to view the corresponding power and voltage values.</p><MotorSelector/><CatalogueDetail slug="motors"/></section></>},{application:"oil-and-gas",content:<><section id="oilfield"><Eyebrow>OILFIELD DRIVES</Eyebrow><h2>Match the motor to the duty.</h2><p className="section-intro">Three-phase oil-filled induction and permanent magnet motors provide the drive for the ESP assembly. Motor selection brings together pump load, available space, power supply and well conditions.</p><div className="motor-options"><article><span className="option-number">01 / INDUCTION</span><h3>Squirrel-cage motors</h3><p>Two-pole asynchronous motors for continuous S1 service. The oilfield catalogue lists a synchronous-speed range of 2,100–4,200 rpm for this family.</p><p className="option-detail">Synchronous speed is the rotating-field speed. Actual induction-motor shaft speed depends on slip and load.</p></article><article><span className="option-number">02 / PERMANENT MAGNET</span><h3>Permanent magnet motors</h3><p>A permanent-magnet rotor works with a compatible variable speed drive. The motor and drive are selected together for the required operating-speed range.</p><p className="option-detail">Specify the required shaft speed and pump duty when requesting the motor and drive combination.</p></article></div>
<SpecificationTable caption="Oilfield motor configuration — selection requirements" headings={["Selection item","What to specify"]} rows={[["Power & load","Required pump shaft power and operating range"],["Electrical supply","Available voltage, current, drive type and cable length"],["Installation geometry","Casing inside diameter, available assembly length and well deviation"],["Thermal conditions","Fluid temperature and cooling flow past the motor"],["Materials & protection","Fluid chemistry and required corrosion-resistant configuration"],["Mechanical interfaces","Protector connection, shaft spline and direction of rotation"],["Monitoring","Required downhole measurements and compatible surface equipment"]]}/>
<div className="motor-package"><div><h3>Select the complete drive assembly.</h3><p>Check the motor together with its protector, power cable and surface drive. Thermal performance and electrical ratings apply to the selected configuration.</p></div><Link href={enquiryHref("Oilfield motor rating sheet","oil-and-gas")} className="text-link">Request motor ratings <ArrowUpRight size={17}/></Link></div>
<p className="spec-note">Model-specific power, voltage, current, dimensions and temperature limits are provided with the motor selection. No geothermal motor ratings are applied to oilfield motors.</p></section></>}]} />;
 if(slug==="cables") return <ProductWorkspace slug={slug} name={product.name} panes={[{application:"geothermal",content:<CableSpecifications/>},{application:"oil-and-gas",content:<OilfieldCableSpecifications/>}]} />;
 if(slug==="protectors") return <ProductWorkspace slug={slug} name={product.name} panes={[{application:"geothermal",content:<><section id="geothermal"><Eyebrow>GEOTHERMAL PROTECTORS</Eyebrow><h2>Tandem design & specifications.</h2><p className="section-intro">Tandem configurations combine labyrinth and diaphragm chambers between the pump and motor.</p><SpecificationTable caption="Geothermal protector overview" headings={["Parameter","Catalogue specification"]} rows={[["Housing outside diameter","172 mm"],["Shaft diameter","43 mm"],["Oil capacity","30 L"],["Axial load options","2,300 / 3,200 kgf"]]}/><CatalogueDetail slug="protectors"/></section></>},{application:"oil-and-gas",content:<><section id="oilfield"><Eyebrow>OILFIELD SEAL SECTIONS</Eyebrow><h2>Configuration options.</h2><p className="section-intro">Modular single-housing and tandem configurations include diaphragm, labyrinth and thrust-bearing arrangements for different drive assemblies.</p><SpecificationTable caption="Selected oilfield seal-section configurations" headings={["Option","Catalogue description"]} rows={[["High-temperature design","Hot-well configuration up to 160 °C for the described modular seal section"],["High-speed variant","Operating rotational frequency up to 12,000 rpm for designated configurations"],["Bearing options","Standard, reinforced and tilting-pad thrust-bearing arrangements"],["Reduced-section variants","Configurations for restricted geometry and other special assembly layouts"]]}/><p className="spec-note">Select the protector model, chamber layout, temperature configuration and thrust-bearing capacity together with the motor and pump.</p></section></>}]} />;
 return <ProductWorkspace slug={slug} name={product.name} panes={[{application:product.applications==="Geothermal"?"geothermal":"oil-and-gas",content:<><section id="technical-data"><GeneralTechnical slug={slug}/></section><CatalogueDetail slug={slug}/></>}]} />;
}

function GeneralTechnical({slug}:{slug:string}){
 if(slug==="gas-handling")return <><Eyebrow>OILFIELD GAS HANDLING</Eyebrow><h2>Manage free gas at the pump inlet.</h2><div className="info-columns three"><div><h3>Gas separation</h3><p>Hydrocyclone modules separate free gas from the liquid stream before it enters the pump.</p></div><div><h3>Gas dispersion</h3><p>Dispersing stages form a more homogeneous gas-liquid mixture for the pumping section.</p></div><div><h3>Combined modules</h3><p>Separator–dispersant units combine both functions within one assembly.</p></div></div><SpecificationTable caption="Gas-stabilizing module operating conditions" headings={["Parameter","Catalogue value"]} rows={[["Maximum fluid density","1,400 kg/m³"],["Maximum single-phase kinematic viscosity","1 mm²/s"],["Production-water pH","5.0–8.5; corrosion-resistant configuration 3.0–9.0"],["Maximum suspended solids","1 g/L"],["Maximum pumped-fluid temperature","170 °C"]]}/><p className="spec-note">The applicable gas-handling model is selected against inlet gas content, fluid properties and the complete ESP configuration.</p></>;
 if(slug==="intakes")return <><Eyebrow>THE PUMP INLET</Eyebrow><h2>Connect the well fluid to the pump.</h2><p className="section-intro">The intake module delivers formation fluid to the pump inlet. Housing, shaft and bearing materials follow the selected configuration.</p><SpecificationTable caption="Oilfield intake components — technical data" headings={["Component","Description"]} rows={[["Housing","Corrosion-resistant steel"],["Radial bearings","Hard alloy"],["Shaft","High-tensile corrosion-resistant steel; Monel options"],["Fasteners","Structural alloy steel; Monel options"]]}/><SpecificationTable caption="Oilfield intake shaft power transmission at 50 / 60 Hz" headings={["Shaft diameter","T11","T12","T13","T14"]} rows={[["20 mm","170 / 200 kW","185 / 220 kW","200 / 240 kW","215 / 260 kW"],["22 mm","230 / 280 kW","250 / 300 kW","270 / 325 kW","290 / 350 kW"],["25 mm","330 / 400 kW","360 / 440 kW","390 / 470 kW","420 / 500 kW"]]}/><p className="spec-note">Power values are listed as 50 / 60 Hz. Confirm the shaft, spline and connection dimensions with the selected pump and protector.</p></>;
 if(slug==="sensors")return <><Eyebrow>DOWNHOLE DATA</Eyebrow><h2>Understand operating conditions.</h2><p className="section-intro">The geothermal motor designation includes downhole sensor options. The sensor and surface equipment are selected as part of the motor configuration.</p><SpecificationTable caption="Motor sensor options" headings={["Code","Sensor manufacturer"]} rows={[["T1","IRZ"],["T2","Etalon"],["T3","Elekton"]]}/><p className="spec-note">Provide the required measurements and existing surface equipment when preparing your enquiry.</p></>;
 if(slug==="controls")return <><Eyebrow>SURFACE DRIVE EQUIPMENT</Eyebrow><h2>Control the pumping system.</h2><SpecificationTable caption="VSD overview" headings={["Parameter","Catalogue specification"]} rows={[["Input voltage","380 / 480 V AC"],["Input frequency","47–63 Hz"],["Output frequency","5–500 Hz"],["Short-term overload","120% for 1 minute"],["Communications","RS485 / Modbus; SCADA and I/O"],["Filtering","Sine-wave filter"]]}/></>;
 return <><Eyebrow>HVOF TECHNOLOGY</Eyebrow><h2>Metallic surface protection.</h2><p className="section-intro">High-velocity oxygen fuel coating is specified as a corrosion-protection option for selected oilfield equipment configurations.</p><SpecificationTable caption="Selected oilfield corrosion-resistant option" headings={["Configuration","Catalogue specification"]} rows={[["CR2C seal-section option","HVOF metallic coating, minimum thickness 150 µm"]]}/><p className="spec-note">Coating selection depends on the component, base material and operating environment. Final applicability is confirmed for the selected configuration.</p></>;
}

export function ServicesPage(){return <main id="main" className="interior-page services-page">
 <FeatureHero label="Services" title="Support through the ESP lifecycle." intro="Project-specific engineering, installation, operating review, inspection and service support for geothermal and oilfield ESP systems." image="/assets/manufacturing-detail.webp" alt="Industrial pumping equipment and pipework" caption="Pumping equipment · technical environment" target="#service-scope" action="Explore services"/>
 <section className="container services-intro" id="service-scope" aria-labelledby="service-scope-title">
  <div className="interior-section-heading"><div><Eyebrow>SERVICE SCOPE</Eyebrow><h2 id="service-scope-title">Support built around<br/>your equipment.</h2></div><p>Service scope is agreed for each project and equipment configuration. The focus is on the technical steps needed to select, install, assess and support the pumping system.</p></div>
  <div className="services-grid">{[
   ["01","Engineering & selection","Review the duty point, well geometry, fluid conditions and electrical requirements to structure the equipment configuration."],
   ["02","Installation & commissioning","Plan project-specific installation and commissioning support for the selected downhole and surface equipment."],
   ["03","Monitoring & troubleshooting","Review available operating data, alarms and field observations to support troubleshooting and operating decisions."],
   ["04","Inspection & failure analysis","Define dismantling, inspection and failure-analysis work for returned or pulled equipment."],
   ["05","Repair & testing","Agree repair and testing scope for selected equipment based on inspection findings and project requirements."],
   ["06","Replacement & optimization","Prepare replacement options and configuration changes where operating conditions or equipment requirements have changed."]
  ].map(([n,title,description])=><article className="service-card" key={n}><span className="service-number">{n}</span><div><h3>{title}</h3><p>{description}</p></div></article>)}</div>
 </section>
 <section className="service-process"><div className="container">
  <div className="interior-section-heading"><div><Eyebrow>START WITH THE FACTS</Eyebrow><h2>A practical service brief.</h2></div><p>Providing the available operating history and equipment details helps define the next technical step without overcomplicating the first request.</p></div>
  <ol className="service-brief-steps">{[
   ["01","Identify the equipment","Share the pump, motor, protector, cable and surface-equipment information that is available."],
   ["02","Share operating history","Include operating hours, well conditions, alarms, electrical measurements and relevant field observations."],
   ["03","Define the requested outcome","State whether the priority is selection, commissioning, troubleshooting, inspection, repair, testing or replacement."]
  ].map(([n,title,description])=><li key={n}><span className="brief-step-number" aria-hidden="true">{n}</span><h3>{title}</h3><p>{description}</p></li>)}</ol>
 </div></section>
 <EnquiryCTA href={enquiryHref("Service support")} title="Prepare your service enquiry." description="Share the equipment details, operating history and the support you need."/>
 </main>;}

export function CompanyPage(){return <main id="main" className="interior-page company-page">
 <FeatureHero label="Company" title="About REPN-FZCO." intro="Equipment selection and project coordination for geothermal and oilfield applications." image="/assets/component-machining.jpg" alt="Precision machining of pumping-equipment components" caption="Precision machining · equipment production" target="#company-profile" action="Our focus"/>
 <CompanyContent/><EnquiryCTA/>
 </main>;}

export function ResourcesPage() {
 return <main id="main" className="interior-page resources-page"><PageHero label="Downloads" title="Catalogues & product data." intro="Explore the REPN-FZCO product guide and download technical data for equipment selection."/>
  <section className="container page-content"><div className="resource-list">{downloads.map(({id,title,description,href,format},index)=><a key={id} id={id} href={href} download className="resource-row"><span className="resource-number" aria-hidden="true"><FileText size={24}/><span>0{index+1}</span></span><div><h2>{title}</h2><p>{description}</p></div><span className="resource-type">{format}</span><span className="resource-download" aria-hidden="true"><Download size={21}/></span></a>)}</div>
   <div className="resources-help"><h2>Looking for other documentation?</h2><p>Detailed oilfield and configuration-specific technical documents can be provided on request where applicable. Certification documents are shared only when their applicability to the selected equipment is confirmed.</p><Button href={enquiryHref("Technical documentation")}>Request documentation</Button></div>
  </section>
 </main>;
}

export function ContactPage() {
 return <main id="main" className="interior-page contact-page"><PageHero label="Contact" title="Let’s discuss your project." intro="Contact REPN-FZCO directly or prepare an enquiry using the form below."/>
  <section className="container contact-layout"><div className="contact-reference-column"><aside><Eyebrow>YOUR CONTACT</Eyebrow><h2>REPN-FZCO</h2><p>Equipment &amp; project enquiries</p><a className="contact-email" href="mailto:office@repnfzco.com">office@repnfzco.com<ArrowUpRight size={20}/></a><div className="contact-hint"><FileText size={24}/><h3>Have a technical brief already?</h3><p>Email your existing project information or equipment documents directly. You do not need to complete the form as well.</p></div></aside><section className="well-reference" aria-labelledby="well-reference-title"><Eyebrow>YOUR WELL PARAMETERS</Eyebrow><h2 id="well-reference-title">Match the numbers.</h2><p>References 1–7 identify the required well parameters in the form.</p><TechnicalImage src="/assets/well-parameters.svg" width={460} height={700} alt="Numbered well sketch: 1 diameter, 2 well depth, 3 dynamic level, 4 static level, 5 flow, 6 temperature, 7 wellhead pressure" caption="Schematic reference. Depths are measured from ground level."/><a className="text-link" href="/downloads/REPN-Equipment-Selection-Questionnaire.docx" download>Download questionnaire (Word)<Download size={17}/></a></section></div><EnquiryForm/></section>
 </main>;
}

export function PrivacyPage(){return <main id="main"><PageHero label="Privacy" title="Your enquiry information." intro="How the website prepares and submits your project enquiry."/><section className="container page-content prose"><h2>Preparing your enquiry</h2><p>Word downloads and print views are prepared in your browser using the information you enter. The form does not save its contents in browser storage. Reloading the page clears the form.</p><h2>Sending an enquiry</h2><p>When direct submission is available and you select Send enquiry, your form details are sent to the website server. A completed Word questionnaire is created and passed to the email delivery service for delivery to office@repnfzco.com. REPN-FZCO uses this information to review and respond to your enquiry.</p><p>When you use Open email app instead, the Word file is downloaded for you to attach and send from your own email account. Downloading, printing or copying alone does not submit an enquiry to REPN-FZCO.</p><h2>Website services</h2><p>The website uses Vercel for hosting. Direct email submission, when configured, uses Resend for email delivery. These services may process the connection and delivery information needed to provide those functions. This website does not include advertising trackers, analytics scripts or externally hosted fonts.</p><h2>Questions about your information</h2><p>Contact office@repnfzco.com with questions about information provided in your enquiry.</p></section></main>;}
